# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flashmastery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for flashmastery
  #pod 'RNMobileCenter'
  #pod 'MobileCenter'
  target 'flashmasteryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
